### ISSUE TITLE
One click deployment page shoud check WP_HOME and WP_SITEURL validity

### ISSUE THREAD

**Issue by cyrille-sg** [Scalingo/scalingo-wordpress#21]
When you create a new app from the one click deploy, it is easy to miss that you must also modify these two fields.
To make it worse, there is no validator when submitting the deployment that these two fields are actually valid.
It will lead to a wordpress unable to do redirection properly, and so users unable to progress in the installation steps

**Comment by SCedricThomas** [comment]
As the fields are required during the app creation and this issue is not really impacting, this issue won't be fixed
